### ISSUE TITLE
Filtering an accession's samples

### ISSUE THREAD

**Issue by vreuter** [pepkit/geofetch#25]
We don't currently have the capability to subset an individual accession and perform a fetch/download for just a subset of the GSM's, do we? Could we implement that? Not sure about frequency of use cases in general, but I'd definitely find it useful for certain fields, especially organism, cell/tissue type, and library strategy / data type.

**Comment by nsheff** [comment]
yes we do!

See here: http://code.databio.org/geofetch/howto-limit/

**Comment by vreuter** [comment]
Nice! That's perfect for what I want to do at the moment; there aren't many GSM's I want to include. 

For cases with more GSM's could we build on this to make them selectable by feature(s)? Something like:
```
# selection.yaml
organism: "Mus musculus"
tissues:
  - "pons"
  - "cerebellum"
strategies:
  - RRBS
  - WGBS
```
would then select a corresponding subset of GSM's.

This seems possible with the metadata downloaded first (as is now I think)? We could then basically compose whatever selections are present to create a conjunctive filter over GSM's. Since the manifest-like file mechanism already exists like in the example docs that you linked, we could leverage that functionality already in place by using the results of the filter operation to create that file, then simply routing execution through the code path that's already used when a file like that is provided up front.

**Comment by nsheff** [comment]
Sure, makes sense. 

I'd say let's be lazy programmers though, and create this feature as soon as we need it. For me, 95% of cases I've just wanted to download everything in a GSE, and for the few that require subselecting, it has not been too much of a pain to build it the sample-by-sample way... but if you actually need this then go for it.

Actually, one other thought...since we're planning to integrate geofetch with caravel (https://github.com/pepkit/caravel/issues/79), this kind of functionality could be handled by a GUI that allows you to filter samples in a table. In other words, geofetch would grab the metadata and give you a table, and you could do your suggestion but using a javascript interface, which would respond in real time to show you which ones you're selecting, which would be nice to graphically see exactly what you're doing.  In that case, I may not bother making it work for geofetch on the CLI.
